### ISSUE TITLE
Nasal runtime error: undefined symbol: active_fpl

### ISSUE THREAD

**Issue by szpajder** [FGMEMBERS/A380-omega#2]
Nasal runtime error: undefined symbol: active_fpl
      at /home/szpajder/stuff/flightgear/Aircraft/A380-omega/Systems/FMGC/fmgc_loop.nas, line 511

Looks like a typo:

    if(active_fpl.active == 1) {

Should be:

    if(active_fpln.active == 1) {

And the FMGC now magically follows flight plan from Route Manager instead of going haywire.

**Comment by IAHM-COL** [comment]
This is awesome fix Thomas. I 'll push this soon.

**Comment by FGDATA** [comment]
Hi All
This is now corrected with
https://github.com/FGMEMBERS/A380-omega/commit/72d09e7502a232e5d01ea70aa8cfb0a1eb34e66b

@Thomas. 
I'll send you an invitation to join FGMEMBERS. This will grant you push access to the FGEMEMBERS repositories. Feel free to fork any aircraft, and pull request your improvements as well. With push access you will be able to merge the pull requests yourself.

In addition, It will also allow you to monitor changes on the aircrafts, as they get better

Have a great day,
IAHM-COL
